spring:
  profiles:
    active: '@spring.profiles.active@'
# https://cloud.spring.io/spring-cloud-sleuth/single/spring-cloud-sleuth.html#_features
# 没有zipkin的依赖，不需要配置zipkin的参数，也不需要配置sampler
#  zipkin:
#    base-url: http://localhost:9411/
#  sleuth:
#    sampler:
#      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
logging:
  pattern:
    # console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}] %clr(%logger{15}){cyan} - %msg%n'
    # console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-B3-ParentSpanId:-},%X{action:-},%X{step:-}] %clr(${PID:-}){magenta} %clr([%15.15t]){faint} %clr(%(%logger{15}<%method:%line>){40}){cyan} %clr(:){faint} %m%n'
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-B3-ParentSpanId:-},%X{action:-},%X{step:-}] %clr(${PID:-}){magenta} %clr([%15.15t]){faint} %clr(%logger{36}.%M:%L){cyan} %clr(:){faint} %m%n'
  level:
    com:
      charles:
        sleuth: DEBUG
    org:
      springframework:
        cloud:
          sleuth: INFO