server:
  port: 9020
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: scs-data-elasticsearch
  data:
    elasticsearch:
      clusterName: elasticsearch
      clusterNodes: localhost:9300
logging:
  level:
    org:
      springframework.data.elasticsearch.core: DEBUG
      elasticsearch.client.transport: TRACE