server:
  servlet:
    context-path: /
spring:
  application:
    name: scs-sleuth-httpclient
  profiles:
    active: '@spring.profiles.active@'
  async:
    enabled: true
    threadpool:
      core-pool-size: 10
      max-pool-size: 2000
      queue-capacity: 400
      thread-name-prefix: AsyncExecutor-

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([${spring.application.name:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-B3-ParentSpanId:-},%X{action:-},%X{step:-}]) %clr(${PID:-}){magenta} %clr([%17.17t]){faint} %clr(%logger{36}#%M:%L){cyan} %clr(:){faint} %m%n'
  level:
    com:
      charles:
        sleuth: INFO
    org:
      springframework:
        cloud:
          sleuth: INFO