#注册服务的端口号
server:
  port: 8078
#应用名称，集群名称需要一致 
spring:
  application:
    name: scs-eureka-slave-02
  profiles:
    active: slave-02
eureka:
  client:
    #是否需要注册到注册中心，因为该项目本身作为服务注册中心，所以为false
    register-with-eureka: false
    #是否需要从注册中心获取服务列表，原因同上，为false
    fetch-registry: false
    #注册服务器的地址：服务提供者和服务消费者都要依赖这个地址
    serviceUrl:
      #defaultZone: http://localhost:${server:port}/eureka
      defaultZone: http://master:8080/eureka/,http://slave-01:8079/eureka/,http://slave-02:8078/eureka/
  instance:
    hostname: slave-02
