server:
  port: 9003
management:
  security:
    enabled: false
  context-path: /
spring:
  application:
    name: scs-admin-server
  mail:
    host: smtp.163.com
    username: xxx@163.com
    password:
    properties:
      mail.debug: false
      mail.smtp.auth: true
  boot:
    admin:
      notify:
        mail:
          to: xxx@qq.com
          from: xxx@163.com
          # ignore-changes: UNKNOWN:UP
          ignore-changes:
            -
              "*:UP" #从任何状态到up状态都不要发邮件通知
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,refresh,heapdump,loggers,auditevents,hystrix.stream
        # endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
# Hystrix支持，如果为true，hystrix库必须在classpath中
feign:
  hystrix:
    enabled: true
#hystrix: command: say-hello: execution: timeout: enabled: false
hystrix:
  threadpool:
    default:
      coreSize: 30
  config:
    stream:
      maxConcurrentConnections: 10
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
        timeout:
          enabled: true
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 30000
