server:
  port: 9021
spring:
  application:
    name: db-query-sharding-jdbc-jpa
  profiles:
    active: sharding-masterslave
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: com.charles.springcloud.supplier.db.base.MySQL5DialectUTF8
    show-sql: false
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr(%logger{15}){cyan} - %msg%n'
  level:
    jdbc:
      sqltiming: INFO
      sqlonly: WARN
      audit: WARN
      resultset: WARN
      resultsettable: WARN
      connection: WARN
    org:
      springframework:
        boot: WARN
eureka:
  client:
    serviceUrl:
      defaultZone: http://master:8081/eureka/
#spring.profiles.active=sharding
#spring.profiles.active=sharding-db
#spring.profiles.active=sharding-tbl
#spring.profiles.active=masterslave
#spring.profiles.active=sharding-masterslave