server:
  port: 10000
spring:
  application:
    name: db-query-sharding-jdbc-mybatis
  profiles:
    active: sharding
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: MySQL5DialectUTF8
    show-sql: false
#spring.profiles.active=sharding-db
#spring.profiles.active=sharding-tbl
#spring.profiles.active=masterslave
#spring.profiles.active=sharding-masterslave
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr(%logger{15}){cyan} - %msg%n'
  level:
    jdbc:
      sqltiming: INFO
      sqlonly: WARN
      audit: WARN
      resultset: WARN
      resultsettable: WARN
      connection: WARN
    org:
      springframework:
        boot: WARN
eureka:
  client:
    serviceUrl:
      defaultZone: http://master:8081/eureka/