server:
  port: 9001
management:
  security:
    enabled: false
  context-path: /
spring:
  application:
    name: scs-consumer-ribbon
  profiles:
    active: slave-02
eureka:
  client:
    serviceUrl:
      defaultZone: http://master:8081/eureka/
hystrix:
  threadpool:
    default:
      coreSize: 50
  config:
    stream:
      maxConcurrentConnections: 10
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
        timeout:
          enabled: true
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 30000
