server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: scs-api-gateway
logging:
  path: logs
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr(%logger{15}){cyan} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{15} - %msg%n'
  level:
    org:
      springframework:
        boot: WARN
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  host:
    connect-timeout-millis: 10000
    connection-request-timeout-millis: 10000
    socket-timeout-millis: 30000
  routes:
    ribbon:
      path: /api/ribbon/**
      stripPrefix: false
      serviceId: scs-consumer-ribbon
    feign:
      path: /api/feign/**
      stripPrefix: false
      serviceId: scs-consumer-feign
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#ribbon:
#  eureka:
#    enabled: false

#scs-consumer-ribbon:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: http://localhost:9010,http://localhost:9011,http://localhost:9012
#    ServerListRefreshInterval: 15000
#    ReadTimeout: 30000
#    ConnectTimeout: 10000