server:
  port: 9091
spring:
  application:
    name: zipkin
  profiles:
    active: service-3
com:
  zipkin:
    serviceName: service-3
    url: http://localhost:9411
    connectTimeout: 6000
    readTimeout: 6000
    flushInterval: 1
    compressionEnabled: true