server:
  port: 9090
spring:
  application:
    name: zipkin
  profiles:
    active: service-2
com:
  zipkin:
    serviceName: service-2
    url: http://localhost:9411
    connectTimeout: 6000
    readTimeout: 6000
    flushInterval: 1
    compressionEnabled: true