server:
  port: 9092
spring:
  application:
    name: zipkin
  profiles:
    active: service-4
com:
  zipkin:
    serviceName: service-4
    url: http://localhost:9411
    connectTimeout: 6000
    readTimeout: 6000
    flushInterval: 1
    compressionEnabled: true